-- ============================================================
-- MBEVHA MOTORS MANAGEMENT SYSTEM (MMMS)
-- Database Seed File
-- ============================================================
-- Run AFTER schema.sql:
--   psql <connection_string> -f seed.sql
--
-- PURPOSE:
--   1. Insert the default administrator account.
--   2. Insert the initial business_info row.
--
-- IMPORTANT — CHANGE THE PASSWORD:
--   The password hash below is a bcrypt hash of:
--   "MbevhaAdmin2026!"
--   Change it immediately after first login via the
--   Settings page in the admin dashboard.
--   To generate a new hash (Node.js):
--     node -e "const b=require('bcrypt'); b.hash('YourNewPassword',12).then(console.log)"
-- ============================================================


-- ============================================================
-- DEFAULT ADMINISTRATOR ACCOUNT
-- ============================================================
-- Username : mbevha_admin
-- Password : MbevhaAdmin2026!  <-- CHANGE THIS IMMEDIATELY
-- ============================================================
INSERT INTO admins (username, password_hash)
VALUES (
    'mbevha_admin',
    -- bcrypt hash of "MbevhaAdmin2026!" with 12 salt rounds
    -- REPLACE this with a hash generated by your own script
    '$2b$12$oDblP3ee74FyHOC0icyURe2u1U72YRRp6HrKU23juWeADQtc6w9xy'
)
ON CONFLICT (username) DO NOTHING;


-- ============================================================
-- INITIAL BUSINESS INFORMATION
-- ============================================================
-- This row is the single source of truth for all public-facing
-- business content on the website.
-- Update via the admin dashboard Business Information page.
-- ============================================================
INSERT INTO business_info (
    business_name,
    motto,
    phone,
    email,
    address,
    about,
    opening_hours,
    whatsapp_number,
    google_maps_link
)
VALUES (
    'Mbevha Motors (Pty) Ltd',
    'Your Trusted Automotive Partner in Limpopo',
    '+27 XX XXX XXXX',
    'info@mbevhamotors.co.za',
    '123 Workshop Street, Thohoyandou, Limpopo, 0950',
    'Mbevha Motors is a trusted automotive workshop based in Thohoyandou, Limpopo. We specialise in vehicle repairs, servicing, and quality used parts. Our experienced technicians are committed to delivering honest, reliable, and affordable automotive services to the community.',
    'Monday to Friday: 07:30 - 17:00 | Saturday: 08:00 - 13:00 | Sunday: Closed',
    '+27 XX XXX XXXX',
    'https://www.google.com/maps/embed?pb=YOUR_EMBED_CODE_HERE'
);


-- ============================================================
-- SEED COMPLETE
-- ============================================================
-- Default admin account created.
-- Initial business_info row inserted.
--
-- ACTION REQUIRED:
--   1. Generate a real bcrypt hash and update admins row.
--   2. Update business_info with real contact details.
--   3. Replace the Google Maps embed URL with the real one.
-- ============================================================
